CREATE TABLE group_branch_options(
	group_id UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE ON UPDATE CASCADE,
	branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE ON UPDATE CASCADE
);