CREATE TABLE votes (
	group_id UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE ON UPDATE CASCADE,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	branch_id UUID NULL REFERENCES branches(id) ON DELETE CASCADE ON UPDATE CASCADE
);