CREATE TABLE IF NOT EXISTS group_place_options(
	group_id UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE ON UPDATE CASCADE,
	place_branch_id UUID NOT NULL REFERENCES place_branches(id) ON DELETE CASCADE ON UPDATE CASCADE
);