CREATE TABLE votes (
	group_id UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE ON UPDATE CASCADE,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	place_branch_id UUID NULL REFERENCES place_branches(id) ON DELETE CASCADE ON UPDATE CASCADE
);